--DROP TABLE Trabajo.RevisionImportesFacE 
CREATE TABLE Trabajo.RevisionImportesFacE (
  fecha DATETIME DEFAULT GETDATE()
, usuario VARCHAR(10)
, facCod SMALLINT NOT NULL	
, facPerCod VARCHAR(6) NOT NULL	
, facCtrCod	INT NOT NULL
, facVersion SMALLINT NOT NULL	
, facEnvSERES VARCHAR(1)	
, facFecEmisionSERES DATETIME	
, Acuama_TOTAL_BASEIMPO MONEY	
, FacE_TOTAL_BASEIMPO MONEY	
, Acuama_TOTAL_IMP_REP MONEY	
, FacE_TOTAL_IMP_REP MONEY
, Acuama_TOTAL_FACTURA MONEY
, FacE_TOTAL_FACTURA MONEY
, Acuama_TOTAL MONEY	
, TOTAL_COBRADO MONEY	
, facEDescEstado VARCHAR(100)	
, facECodEstado VARCHAR(8)	
, ERROR_MSG VARCHAR (250)
)

