--TRUNCATE TABLE dbo.serviciosBloques
INSERT INTO dbo.serviciosBloques
VALUES(3, 4, 'ALTA Y CONTADORES'),
(3, 5, 'ALTA Y CONTADORES'),
(3, 13, 'ALTA Y CONTADORES'),
(3, 14, 'ALTA Y CONTADORES'),
(3, 15, 'ALTA Y CONTADORES');

INSERT INTO dbo.serviciosBloques
VALUES(4, 12, 'ACOMETIDAS'),
(4, 101, 'ACOMETIDAS'),
(4, 102, 'ACOMETIDAS');


INSERT INTO dbo.serviciosBloques
VALUES(5, 6, 'CAMIÓN SUCCIONADOR'),
(5, 7, 'CAMIÓN SUCCIONADOR');

INSERT INTO dbo.serviciosBloques
VALUES(6, 16, 'SATÉLITES SUMINISTRO Y ANALÍTICAS'),
(6, 8, 'SATÉLITES SUMINISTRO Y ANALÍTICAS'),
(6, 9, 'SATÉLITES SUMINISTRO Y ANALÍTICAS'),
(6, 10, 'SATÉLITES SUMINISTRO Y ANALÍTICAS');

INSERT INTO dbo.serviciosBloques
VALUES(7, 11, 'SATÉLITES DEPURACIÓN');

INSERT INTO dbo.serviciosBloques
VALUES(0, 2, '(CUATRIMESTRAL O MENSUAL)')
, (0, 3, '(CUATRIMESTRAL O MENSUAL)')
, (0, 99, '(CUATRIMESTRAL O MENSUAL)')
, (0, 100, '(CUATRIMESTRAL O MENSUAL)')
, (0, 103, '(CUATRIMESTRAL O MENSUAL)')
, (0, 104, '(CUATRIMESTRAL O MENSUAL)')
, (0, 105, '(CUATRIMESTRAL O MENSUAL)')
, (0, 106, '(CUATRIMESTRAL O MENSUAL)')
, (0, 107, '(CUATRIMESTRAL O MENSUAL)')
, (0, 110, '(CUATRIMESTRAL O MENSUAL)')
, (0, 111, '(CUATRIMESTRAL O MENSUAL)')


INSERT INTO dbo.serviciosBloques
VALUES(99, 1, '(ENTREGAS A CUENTA O CUATRIMESTRALES O MENSUAL)')


INSERT INTO serviciosBloques VALUES
(17, 17, 'LIQUIDACION TRSU')


