--SELECT  dbo.fDataBaseNameSOA('004')
--SELECT @@SERVERNAME
ALTER FUNCTION [dbo].[fDataBaseNameSOA](@cobCodExplo VARCHAR(20))
RETURNS VARCHAR(25)
BEGIN

DECLARE @BBDD AS VARCHAR(25);

SELECT @BBDD  = CASE @@SERVERNAME WHEN 'SQLDESA41' THEN 'ACUAMA_%s_DESA'
								  WHEN 'SQLPRE41' THEN 'ACUAMA_%s_PRE'
								  WHEN 'SQLPRE42' THEN 'ACUAMA_%s_PRE'
								  ELSE 'ACUAMA_%s' END;
--ACUAMA_GUADALAJARA_PRE
SELECT @BBDD = CASE @cobCodExplo
				WHEN '001' THEN FORMATMESSAGE(@BBDD, 'ALMADEN')
				WHEN '002' THEN FORMATMESSAGE(@BBDD, 'ALAMILLO')
				WHEN '003' THEN FORMATMESSAGE(@BBDD, 'SVB')
				WHEN '004' THEN FORMATMESSAGE(@BBDD, 'GUADALAJARA')
				WHEN '007' THEN FORMATMESSAGE(@BBDD, 'VALDALIGA')
				WHEN '011' THEN FORMATMESSAGE(@BBDD, 'BIAR')
				WHEN '015' THEN FORMATMESSAGE(@BBDD, 'RIBADESELLA')
				ELSE '' END;



RETURN @BBDD;

END
GO


