
 INSERT INTO dbo.otInspeccionesApto_Melilla(otiaDescripcion, otiaColumna, otiaServicio, otiaCritico, otiaReqisitoReglamentoCTE, otiaOrden)
 VALUES('LLAVE DE PASO Y ARQUETA EN ACERA', 'llavepaso', 'CONTADORES', 'SI',  1, 1),
('TUBERÍA DE ENTRADA AL EDIFICIO AL DESCUBIERTO EN UN TRAMO DE 35 CM EN EL QUE PRESENTA TOTAL HORIZONTALIDAD', 'tuberiaentrada', 'CONTADORES', 'SI', 1, 2),
('TRAMO DE TUBERÍA EN EL INTERIOR DE UN ARMARIO CON PUERTA DE 300X250X160 MM, INSTALADA EN FACHADA DEL EDIFICIO A UNA ALTURA DE ENTRE 0,90 M Y 1,5 M DESDE EL NIVEL DEL SUELO', 'arquetaconpuerta', 'CONTADORES', 'NO', 1, 3),
('JUEGO DE LLAVE DE ENTRADA Y SALIDA', 'juegollaves', 'CONTADORES', 'SI', 0, 4),
('VÁLVULA DE RETENCIÓN', 'valvularetencion', 'CONTADORES', 'SI', 0, 5), 
('DIÁMETRO ROSCA ENTRADA', 'tamanoroscae', 'CONTADORES', 'NO',  0, 6),
('DIÁMETRO ROSCA SALIDA', 'tamanoroscas', 'CONTADORES', 'NO',  0, 7),
('ESTADO DE CONSERVACIÓN DE LA INSTALACIÓN HIDRÁULICA (BUENO, MALO)', 'estadocontador', 'CONTADORES', 'SI',  0, 8);

 INSERT INTO dbo.otInspeccionesApto_Melilla(otiaDescripcion, otiaColumna, otiaServicio, otiaCritico, otiaReqisitoReglamentoCTE, otiaOrden)
 VALUES
('UBICACIÓN EN PLANTA BAJA DEL EDIFICIO SEPARA DE DEPENDENCIAS DESTINADAS A GAS Y ELECTRICIDAD', 'plantabaja', 'BATERIAS', 'SI', 1, 1),
('UBICACIÓN EN ZONA DE FÁCIL ACCESO Y USO COMÚN DEL INMUEBLE, LO MÁS CERCA POSIBLE DE LA LLAVE DE PASO DEL EDIFICIO', 'facilacceso', 'BATERIAS', 'NO', 1, 2),
('PUERTA DEL  ARMARIO IDENTIFICADA CON UNA O MÁS HOJAS DEJANDO LIBRE AL ABRIRSE TODO EL ANCHO DEL MISMO', 'armario12', 'BATERIAS', 'NO', 1, 3),
('CUARTO DOTADO DE ILUMINACIÓN ELÉCTRICA ESTANCA ', 'instestanca', 'BATERIAS', 'SI', 1, 4),
('PILETA DE GOTEO CON DESAGÜE A LA ALCANTARILLA CON COTA ADECUADA', 'desague', 'BATERIAS', 'SI', 1, 5),
('EL ACCESO AL ALJIBE Y/O GRUPO DE PRESIÓN SEPARADO DE LA PUERTA DE ACCESO AL CUARTO DE CONTADORES Y LA ZONA DE LECTURA', 'aljibe', 'BATERIAS', 'NO', 1, 6),
('CUARTO O ARMARIO DESTINADO EN EXCLUSIVA A INSTALACIONES DE CONTADORES DE AGUA', 'armariounico', 'BATERIAS', 'NO',1, 7) ,
('CERRADURA DE LOS MODELOS ACEPTADOS POR EL SERVICIO', 'cerradura', 'BATERIAS', 'NO', 1, 8),
('BATERÍA EN CIRCUITO CERRADO CON TRES TUBOS HORIZONTALES COMO MÁXIMO', 'tecnicas_bat_9', 'BATERIAS', 'SI',1, 9), 
('FILA SUPERIOR DE CONTADORES MÁXIMO A 1,60 M DE ALTURA DESDE EL SUELO O PUNTO DESDE EL QUE PISA EL LECTOR O INSPECTOR Y MÍNIMO A 0,50 M METROS DEL TECHO', 'tecnicas_bat_10', 'BATERIAS', 'NO', 0, 10),
('FILA INFERIOR SITUADA COMO MÍNIMO A 0,50 M DE ALTURA DESDE EL SUELO Y SEPARACIÓN ENTRE FILAS DE 0,25 M. DISTANCIA DEL FONDO DE LA PARED 0,16 Y FILAS DE 3 M DE ANCHO', 'tecnicas_bat_11', 'BATERIAS', 'NO', 1, 11),
('LOS RAMALES PRESENTAN HORIZONTALIDAD EN UN TRAMO MÍNIMO DE 35 CM', 'tecnicas_bat_12', 'BATERIAS', 'SI', 0, 12),
('LLAVES DE ENTRADA Y SALIDA EN CONTADORES', 'llavescontadores', 'BATERIAS', 'SI',1, 13), 
('LA BRIDA DE CONEXIÓN A LA LLAVE DE ENTRADA A CONTADOR OVALADA, ORIENTADA DE FORMA QUE EL EJE MAYOR SEA PERPENDICULAR A LA PARED', 'tecnicas_bat_15', 'BATERIAS', 'NO', 1, 14),
('VÁLVULA DE RETENCIÓN INCORPORADA EN LOS CONTADORES DE SALIDA.', 'tecnicas_bat_16', 'BATERIAS', 'SI', 1, 15),
('LLAVES PROVISTAS DE MANGUITO CON JUNTA INCORPORADA, SIN CONTRARROSCAS', 'tecnicas_bat_17', 'BATERIAS', 'SI', 1, 16),
('BATERÍA NO SIMULADA: LLAVE DE CORTE, BATERÍA EN CIRCUITO CERRADO, LLAVE DE ENTRADA AL CONTADOR, LLAVE DE SALIDA DEL CONTADOR, VÁLVULA DE RETENCIÓN, GRIFO DE COMPROBACIÓN, LATIGUILLO, TAPA CIEGA.', 'tecnicas_bat_18', 'BATERIAS', 'SI', 0, 17),
('BATERÍA NORMALIZADA (GALVANIZADA O PLÁSTICO)', 'tecnicas_bat_19', 'BATERIAS', 'NO', 1, 18),
('LLAVES DE SALIDA ROSCA 3/4"', 'tecnicas_bat_20', 'BATERIAS', 'SI', 1, 19),
('VÁLVULA RETENCIÓN ENTRADA BATERÍA', 'valvularetencionentrada', 'BATERIAS', 'NO', 0, 20),
('CUADRO DE CLASIFICACIÓN EN LUGAR VISIBLE POR EL QUE SE PUEDE IDENTIFICAR A QUÉ VIVIENDA CORRESPONDE UN CONTADOR DETERMINADO POR SU POSICIÓN EN LA BATERÍA', 'idvivienda', 'BATERIAS', 'NO', 1, 21),
('TODOS LOS CONTADORES CORRECTAMENTE INSTALADOS Y LEGIBLES', 'tecnicas_bat_13', 'BATERIAS', 'NO',  0, 22),
('NUMERO CONTADORES EN BATERÍA', 'tecnicas_bat_1', 'BATERIAS', 'NO',  0, 23),
('CALIBRES CONTADORES', 'calibrebat', 'BATERIAS', 'NO',  0, 24),
('ROSCA ENTRADA', 'roscacontadorebat', 'BATERIAS', 'NO',  0, 25),
('ROSCA SALIDA', 'roscacontadorsbat', 'BATERIAS', 'NO',  0, 26),
('ESTADO DE CONSERVACIÓN DE LA INSTALACIÓN HIDRÁULICA (BUENO, MALO)', 'estadobat', 'BATERIAS', 'NO',  0, 27)

