--DROP FUNCTION fLiquidaciones_RIBADESELLA
ALTER FUNCTION [dbo].[fLiquidaciones_RIBADESELLA](@Liq AS dbo.tLiquidaciones_RIBADESELLA READONLY, @liqTipoId INT) 
RETURNS TABLE 
RETURN
SELECT PK
,	EJ
,	ENTEMI
,	AYTO
,	TRIBUTO
,	ANUALIDAD
,	NUMLIQ
,	NOMCER
,	PRINCI
,	INIVOL
,	FINVOL
,	CONTRI
,	DNI
,	SIGLAS
,	LUGAR
,	POBLACION
,	MUNICIPIO
,	PROVINCIA
,	CPP
,	CONCEPTO
,	CLAVE1
,	CONYUGE
,	NIFCON
,	FECHACER
,	DETALLE
,	OTRA1
,	OTRA2
,	LOTE
,	MODONOT
,	FECHALIQ
,	PERIODO
,	FECHAFIR
,	REPRE
,	DIREREPRE
,	MUNIREPRE
,	PROVIREPRE
,	CPPREPRE
,	IMPENT
,	FINGRE
,	ORGOFI
,	IVA
,	FECHA_APREMIO
,	CODAGUA180
,	IMPAGUA180
,	IVAAGUA180
,	CODBASURA180
,	IMPBASURA180
,	CODALC180
,	IMPALC180
,	CODMIN180
,	IMPMIN180
,	CODTCONT180
,	IMPTCONT180
,	IVATCONT180
,	CODCANON180
,	IMPCANON180
,	CODOTRO1180
,	IMPOTRO1180
,	CODOTRO2180
,	IMPOTRO2180
,	PRESCRIPCION
,	TOTAL_BASE 
,	TOTAL_IVA 
---------------------------
--TEXTO PLANO: RESULT
---------------------------
,	RESULT = [dbo].[fBlanquearCaracteresEspeciales](CONCAT(
	EJ
,	ENTEMI
,	AYTO
,	TRIBUTO
,	ANUALIDAD
,	NUMLIQ
,	NOMCER
,	PRINCI
,	INIVOL
,	FINVOL
,	CONTRI
,	DNI
,	SIGLAS
,	LUGAR
,	POBLACION
,	MUNICIPIO
,	PROVINCIA
,	CPP
,	CONCEPTO
,	CLAVE1
,	CONYUGE
,	NIFCON
,	FECHACER
,	DETALLE
,	OTRA1
,	OTRA2
,	LOTE
,	MODONOT
,	FECHALIQ
,	PERIODO
,	FECHAFIR
,	REPRE
,	DIREREPRE
,	MUNIREPRE
,	PROVIREPRE
,	CPPREPRE
,	IMPENT
,	FINGRE
,	ORGOFI
,	IVA
----------------------------
--IMPAGADOS AYUNTAMIENTO: @liqTipoId=1: 
--agua, basura, alcantarillado, canon de saneamiento, etc. (tributo 180)

--IMPAGADOS F211 DE IMPUESTO DE AFECCIONES AMBIENTALES @liqTipoId=2: 
--canon de saneamiento  (tributo 181)
,	CASE(@liqTipoId) WHEN 1 THEN FECHA_APREMIO	ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN CODAGUA180		ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN IMPAGUA180		ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN IVAAGUA180		ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN CODBASURA180	ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN IMPBASURA180	ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN CODALC180		ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN IMPALC180		ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN CODMIN180		ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN IMPMIN180		ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN CODTCONT180	ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN IMPTCONT180	ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN IVATCONT180	ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN CODCANON180	ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN IMPCANON180	ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN CODOTRO1180	ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN IMPOTRO1180	ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN CODOTRO2180	ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN IMPOTRO2180	ELSE '' END
,	CASE(@liqTipoId) WHEN 1 THEN PRESCRIPCION	ELSE '' END
))

FROM @Liq;



GO


