--DROP TABLE  [Trabajo].[VERSION_CNS_COMUNITARIOS]
CREATE TABLE [Trabajo].[VERSION_CNS_COMUNITARIOS](
	[cnsVersion] [varchar](10) NOT NULL,
	[cnsDescripcion] [varchar](250) NOT NULL,
	 CONSTRAINT PK_VERSION_CNS_COMUNITARIOS PRIMARY KEY (cnsVersion)
	)




