--SELECT * FROM dbo.liquidacionesTipos

INSERT INTO dbo.liquidacionesTipos 
VALUES 
(0, 'SIN ORGANISMO', NULL, '', '', '', ''),
(1, 'AYUNTAMIENTO DE RIBADESELLA', 1, '056', '180','TASA AGUA,BASURA,ALCANTARILLADO', 'AP'),
(2, 'JUNTA DE SANEAMIENTO DEL PRINCIPADO DE ASTURIAS', 2, '901', '181', 'CANON SANEAMIENTO', 'CC' );


