/*
DECLARE @otiserscd SMALLINT = 1;
DECLARE @otisercod SMALLINT = 80;
DECLARE @otinum INT = 104857;
EXEC dbo.otInspecciones_Melilla_ObtenerDatos @otiserscd, @otisercod,  @otinum, 1
*/

ALTER PROCEDURE dbo.otInspecciones_Melilla_ObtenerDatos(@otiserscd SMALLINT = NULL, @otisercod SMALLINT=NULL, @otinum INT=NULL, @objectid INT=NULL)
AS

WITH FILA AS(
SELECT * 
FROM OTInspecciones_Melilla
WHERE  (@objectid IS NULL AND otiserscd=@otiserscd AND otisercod = @otisercod AND otinum = @otinum) 
		OR
	   (objectid = @objectid)
), P AS(
SELECT u.Clave, u.Valor
FROM FILA
CROSS APPLY (
    VALUES 
        ('objectid', CAST(objectid AS VARCHAR(250))),
        ('globalid', CAST(globalid AS VARCHAR(250))),
        ('fecha_y_hora_de_entrega_efectiv', CAST(fecha_y_hora_de_entrega_efectiv AS VARCHAR(250))),
        ('numeroinspeccion', CAST(numeroinspeccion AS VARCHAR(250))),
        ('zona', CAST(zona AS VARCHAR(250))),
        ('tipologiacsv', CAST(tipologiacsv AS VARCHAR(250))),
        ('contrato', CAST(contrato AS VARCHAR(250))),
        ('domicilio', CAST(domicilio AS VARCHAR(250))),
        ('ruta1', CAST(ruta1 AS VARCHAR(250))),
        ('ruta2', CAST(ruta2 AS VARCHAR(250))),
        ('ruta3', CAST(ruta3 AS VARCHAR(250))),
        ('ruta4', CAST(ruta4 AS VARCHAR(250))),
        ('ruta5', CAST(ruta5 AS VARCHAR(250))),
        ('ruta6', CAST(ruta6 AS VARCHAR(250))),
        ('incidencias', CAST(incidencias AS VARCHAR(250))),
        ('tipoincidencia', CAST(tipoincidencia AS VARCHAR(250))),
        ('servicio', CAST(servicio AS VARCHAR(250))),
        ('direccion_1', CAST(direccion_1 AS VARCHAR(250))),
        ('viviendas', CAST(viviendas AS VARCHAR(250))),
        ('facilacceso', CAST(facilacceso AS VARCHAR(250))),
        ('armariobuenestado', CAST(armariobuenestado AS VARCHAR(250))),
        ('arquetaconpuerta', CAST(arquetaconpuerta AS VARCHAR(250))),
        ('arquetafachada', CAST(arquetafachada AS VARCHAR(250))),
        ('arquetanivelsuelo', CAST(arquetanivelsuelo AS VARCHAR(250))),
        ('caracteristicas', CAST(caracteristicas AS VARCHAR(250))),
		('ncontadores', CAST(ncontadores AS VARCHAR(250))),
        ('calibrecontador', CAST(calibrecontador AS VARCHAR(250))),
        ('calibre13', CAST(calibre13 AS VARCHAR(250))),
        ('calibre15', CAST(calibre15 AS VARCHAR(250))),
        ('calibre20', CAST(calibre20 AS VARCHAR(250))),
        ('calibre32', CAST(calibre32 AS VARCHAR(250))),
        ('calibre40', CAST(calibre40 AS VARCHAR(250))),
        ('calibre50', CAST(calibre50 AS VARCHAR(250))),
        ('materialtuberias', CAST(materialtuberias AS VARCHAR(250))),
        ('llavepaso', CAST(llavepaso AS VARCHAR(250))),
        ('juegollaves', CAST(juegollaves AS VARCHAR(250))),
        ('valvularetencion', CAST(valvularetencion AS VARCHAR(250))),
        ('tuberiaentrada', CAST(tuberiaentrada AS VARCHAR(250))),
        ('roscacontadore', CAST(roscacontadore AS VARCHAR(250))),
        ('tamanoroscae', CAST(tamanoroscae AS VARCHAR(250))),
        ('roscacontadors', CAST(roscacontadors AS VARCHAR(250))),
        ('tamanoroscas', CAST(tamanoroscas AS VARCHAR(250))),
        ('direccion_bat', CAST(direccion_bat AS VARCHAR(250))),
        ('viviendasbat', CAST(viviendasbat AS VARCHAR(250))),
        ('llavescasa', CAST(llavescasa AS VARCHAR(250))),
        ('llavescontadores', CAST(llavescontadores AS VARCHAR(250))),
        ('situacionbat', CAST(situacionbat AS VARCHAR(250))),
        ('plantabaja', CAST(plantabaja AS VARCHAR(250))),
        ('accesobat', CAST(accesobat AS VARCHAR(250))),
        ('usocomun', CAST(usocomun AS VARCHAR(250))),
        ('llavepasocerca', CAST(llavepasocerca AS VARCHAR(250))),
        ('sepradogas', CAST(sepradogas AS VARCHAR(250))),
        ('armarioid', CAST(armarioid AS VARCHAR(250))),
        ('armariounico', CAST(armariounico AS VARCHAR(250))),
        ('armario12', CAST(armario12 AS VARCHAR(250))),
        ('instestanca', CAST(instestanca AS VARCHAR(250))),
        ('desague', CAST(desague AS VARCHAR(250))),
        ('aljibe', CAST(aljibe AS VARCHAR(250))),
        ('idvivienda', CAST(idvivienda AS VARCHAR(250))),
		('tecnicas_bat_1', CAST(tecnicas_bat_1 AS VARCHAR(250))),
        ('calibrebat', CAST(calibrebat AS VARCHAR(250))),
        ('tecnicas_bat_2', CAST(tecnicas_bat_2 AS VARCHAR(250))),
        ('tecnicas_bat_3', CAST(tecnicas_bat_3 AS VARCHAR(250))),
        ('tecnicas_bat_4', CAST(tecnicas_bat_4 AS VARCHAR(250))),
        ('tecnicas_bat_5', CAST(tecnicas_bat_5 AS VARCHAR(250))),
        ('tecnicas_bat_6', CAST(tecnicas_bat_6 AS VARCHAR(250))),
        ('tecnicas_bat_7', CAST(tecnicas_bat_7 AS VARCHAR(250))),
        ('tecnicas_bat_8', CAST(tecnicas_bat_8 AS VARCHAR(250))),
        ('tecnicas_bat_9', CAST(tecnicas_bat_9 AS VARCHAR(250))),
        ('tecnicas_bat_10', CAST(tecnicas_bat_10 AS VARCHAR(250))),
        ('tecnicas_bat_11', CAST(tecnicas_bat_11 AS VARCHAR(250))),
        ('tecnicas_bat_12', CAST(tecnicas_bat_12 AS VARCHAR(250))),
        ('tecnicas_bat_13', CAST(tecnicas_bat_13 AS VARCHAR(250))),
        ('tecnicas_bat_14', CAST(tecnicas_bat_14 AS VARCHAR(250))),
        ('tecnicas_bat_15', CAST(tecnicas_bat_15 AS VARCHAR(250))),
        ('tecnicas_bat_16', CAST(tecnicas_bat_16 AS VARCHAR(250))),
        ('tecnicas_bat_17', CAST(tecnicas_bat_17 AS VARCHAR(250))),
        ('tecnicas_bat_18', CAST(tecnicas_bat_18 AS VARCHAR(250))),
        ('tecnicas_bat_19', CAST(tecnicas_bat_19 AS VARCHAR(250))),
        ('tecnicas_bat_20', CAST(tecnicas_bat_20 AS VARCHAR(250))),
		('roscacontadorebat', CAST(roscacontadorebat AS VARCHAR(250))),
        ('tamanoroscaebat', CAST(tamanoroscaebat AS VARCHAR(250))),
        ('roscacontadorsbat', CAST(roscacontadorsbat AS VARCHAR(250))),
        ('tamanoroscasbat', CAST(tamanoroscasbat AS VARCHAR(250))),
        ('valvularetencionentrada', CAST(valvularetencionentrada AS VARCHAR(250))),
        ('cerradura', CAST(cerradura AS VARCHAR(250))),
        ('estadobat', CAST(estadobat AS VARCHAR(250))),
        ('usuario', CAST(usuario AS VARCHAR(250))),
        ('observaciones', CAST(observaciones AS VARCHAR(250))),
        ('apto', CAST(apto AS VARCHAR(250))),
        ('aptono5', CAST(aptono5 AS VARCHAR(250))),
        ('aptono6', CAST(aptono6 AS VARCHAR(250))),
        ('aptono2', CAST(aptono2 AS VARCHAR(250))),
        ('aptono3', CAST(aptono3 AS VARCHAR(250))),
        ('created_date', CAST(created_date AS VARCHAR(250))),
        ('created_user', CAST(created_user AS VARCHAR(250))),
        ('last_edited_date', CAST(last_edited_date AS VARCHAR(250))),
        ('last_edited_user', CAST(last_edited_user AS VARCHAR(250))),
        ('countattachments', CAST(countattachments AS VARCHAR(250))),
        ('attachid', CAST(attachid AS VARCHAR(250))),
        ('url', CAST(url AS VARCHAR(250))),
        ('attachid_last', CAST(attachid_last AS VARCHAR(250))),
        ('url_final', CAST(url_final AS VARCHAR(250))),
        ('domicilio_v2', CAST(domicilio_v2 AS VARCHAR(250))),
        ('calibre65', CAST(calibre65 AS VARCHAR(250))),
        ('calibre80', CAST(calibre80 AS VARCHAR(250))),
        ('calibre100', CAST(calibre100 AS VARCHAR(250))),
        ('estadocontador', CAST(estadocontador AS VARCHAR(250))),
        ('tecnicas_bat_7_1', CAST(tecnicas_bat_7_1 AS VARCHAR(250))),
        ('tecnicas_bat_7_2', CAST(tecnicas_bat_7_2 AS VARCHAR(250))),
		 ('tecnicas_bat_7_3', CAST(tecnicas_bat_7_3 AS VARCHAR(250))),
        ('juegollavesbat', CAST(juegollavesbat AS VARCHAR(250))),
        ('realizado_user', CAST(realizado_user AS VARCHAR(250))),
        ('x', CAST(x AS VARCHAR(250))),
        ('y', CAST(y AS VARCHAR(250))),
        ('otiserscd', CAST(otiserscd AS VARCHAR(250))),
        ('otisercod', CAST(otisercod AS VARCHAR(250))),
        ('otinum', CAST(otinum AS VARCHAR(250))),
        ('UsuarioCarga', CAST(UsuarioCarga AS VARCHAR(250))),
        ('FechaCarga', CAST(FechaCarga AS VARCHAR(250)))
		) AS u (Clave, Valor))

SELECT Clave=Clave, Valor=UPPER(LTRIM(RTRIM(Valor))) FROM P WHERE Valor IS NOT NULL;

GO